# Smithery configuration for Twitch MCP Server
projectType: docker
build:
  dockerfilePath: Dockerfile
  dockerBuildPath: .
  imageTag: twitch-mcp-server
  buildArgs: {}
ports:
  - 8080
healthCheck:
  path: /q/health
  port: 8080
environment: {}
deployment:
  containerPort: 8080