# Smithery configuration file
# https://smithery.ai/docs/build/project-config

projectType: docker
build:
  dockerfilePath: Dockerfile.smithery
  dockerBuildPath: .
  imageTag: twitch-mcp-server

deployment:
  containerPort: 8080
  # healthCheckPath: /mcp  # Optional: enable after verifying endpoint