# Smithery configuration file
# https://smithery.ai/docs/build/project-config

projectType: docker
build:
  dockerfilePath: smithery/Dockerfile
  dockerBuildPath: smithery
  imageTag: twitch-mcp-server

deployment:
  containerPort: 8080